### ISSUE TITLE
Add Gte operator

### ISSUE THREAD

**Issue by asdine** [heetch/regula#104]

**Comment by YassineE** [comment]
For a Gte comparison between booleans, is the following true?
```go
true >= true : true
true >= false : true
false >= true : false
false >= false: true
```

cc @tealeg

**Comment by YassineE** [comment]
From what I understand in what @tealeg did in 0.7 I am right.

https://github.com/heetch/regula/blob/b79b8edceafa6f3c5d7461ba29f83cbbb94ddb40/rule/eq_expr.go#L640-L658
