### ISSUE TITLE
Wrong ruleset returned with Eval method

### ISSUE THREAD

**Issue by asdine** [heetch/regula#108]
While QA'ing the v0.6 I encountered an annoying bug:

Let A a ruleset at path `a`, let AB a ruleset at path `a/b`:

- Create ruleset A: version `XYZ`
- Create ruleset AB: version `JKL`

In etcd:
```
/a/XYZ
/a/b/JKL
```

The store `Latest` method, which is used by the `Eval` endpoint, when called with the former path returns the latter.

```
rs, err := store.Latest(ctx, "/a") // returns /a/b
```

**Comment by YassineE** [comment]
Maybe this one should also be applied on [0.7](https://github.com/heetch/regula/milestone/1).
To verify.

**Comment by asdine** [comment]
The problem here came because of the use of `/` as a separator between the path and the version.
It shouldn't be a problem anymore normally thanks to your change of the separator to `!`
