### ISSUE TITLE
Possible conditional segmentation

### ISSUE THREAD

**Issue by drommk** [heetch/regula#11]
One powerful aspect of firebase is that it makes it possible to easily evaluate a condition to a given percentile of the users. 

This is really useful for progressive rollout strategies and A/B testing. 

Having such a behavior and making it easily customizable would be a game changer in terms of mobile adoption, especially if we couple it with a feature flag-focused strategy

Simple use case : 
- release feature A to 5% of the whole user base

Complicated use case 
- I want to A/B test feature Z in Morocco
- I need two groups, each being affected 3% of the mobile devices
- mobile client needs to know what group user is in. 

In both cases groups results should be idempotent

**Comment by drommk** [comment]
NB : this can be done in 2 steps 
- evaluation of the group(s) user belong to
- usage of that group/key as input param for later rules

**Comment by drommk** [comment]
It seems like you already started addressing some of those. Maybe we can associate the corresponding decisions to this ticket?

**Comment by asdine** [comment]
Indeed #80 is supposed to help to achieve some of these cases. 
It is described here: https://github.com/heetch/boost-workflow/blob/master/projects/RegulaUI/2-product%20specs.md#hashing-and-grouping

:information_source: Currently, this release is focused on the huge work of adding a UI and a rule syntax, so the A/B testing features have only been slightly introduced to the project.
Most of the power will be unleased starting from the 0.7
