### ISSUE TITLE
Define Parser for symbolic expression language

### ISSUE THREAD

**Issue by tealeg** [heetch/regula#17]
Create a `Parser` that wraps the `Scanner` defined in #16. 
The parser will sequentially scan for Tokens using its Scanner, it will have the ability to backtrack when required using a token buffer.  At every point, the Parser will have expectations. 

The top level parser will return a `regula.Rule` type. It will always expect the next token to be one of the following:
- EOF
- The beginning of an s-expression list-form that evaluates to boolean type
- A comment
- an atom of boolean type

The behaviour of the parser having scanned one of this tokens will switch.  If we got an EOF, we will either return the outermost form of the symbolic expression tree, or, if we are not at the root level of that tree, we shall exit with an error condition. 
If the token is the beginning of an s-expression list form, we call a `scanSExpressionListScanner` function that will return a `regula.Expr` with a defined type.
If the token is the beginning of a comment, we'll return a `regula.Comment` (a special kind of `regula.Expr`). 
If the token is an atom, we'll return a `regula.Value` type or an operator expression.   When an operator expression is returned we'll use it to make type expecations for the remaining members of an s-expression list form. 

Note that the parser will need to recursively append regula structures to ther parents to build the entire s-expression tree.

**Comment by jhchabran** [comment]
@tealeg Can we close this or is there something missing?

**Comment by tealeg** [comment]
It can be closed.
