### ISSUE TITLE
New endpoint: Get a ruleset

### ISSUE THREAD

**Issue by asdine** [heetch/regula#24]
Endpoint: `GET /rulesets/<path>`
This endpoint must return the ruleset related to the given path. By default it returns the latest version.

If the `version` (string) param is specified and non empty, the endpoint returns the specified version
Must return 404 if the path or the version doesn't exist or is malformed.

Returned payload:

```js
 {
        "path": "",
        "version": "",
        "ruleset": {}, // regula.Ruleset
        "signature": {
            "params": [{"<name>": "<type>"}],
            "returns": "<type>"
        }
        "versions": ["", ""] // list of string representing all the existing versions of the ruleset sorted by ascending order
    }
```

**Comment by YassineE** [comment]
Closing this, fixed in #55.
