### ISSUE TITLE
New operators: Simple arithmetic

### ISSUE THREAD

**Issue by asdine** [heetch/regula#26]
Addition: +
Signature: `(+ number...) -> number`
Kind: "add"

Subtraction: -
Signature: `(- number...) -> number`
Kind: "sub"

Multiplication: *
Signature: `(* number...) -> number`
Kind: "mult"

Division: /
Signature: `(/ number...) -> float`
Kind: "div"

Modulo: %
Signature: `(% int...) -> int`
Kind: "mod"

**Comment by tealeg** [comment]
@asdine I not sure what the modulo of a series of more than 2 integers would be?  Every language I'm aware of only accepts to parameters to the modulo function.

Just off the top of my head I guess you could implement it as:
```
( % (% (% a b) c) d)) 
```
... but it's not clear when this would be useful.

**Comment by asdine** [comment]
@tealeg Me neither actually, I suggest to go with an arity of 2, following [Wikipedia's definition](https://en.wikipedia.org/wiki/Modulo_operation):

> In computing, the modulo operation finds the remainder after division of one number by another (sometimes called modulus).

**Comment by tealeg** [comment]
:+1:
