### ISSUE TITLE
New operators: Hashing

### ISSUE THREAD

**Issue by asdine** [heetch/regula#28]
In order to identify and change hashing algorithm, we need to use a unique name for these functions so we can later add new ones and choose the ones that suit our needs.

The first hash function we will introduce is the FNV hash, which is a fast, non-cryptographic algorithm.
Signature: `(fnv any) -> int`
Kind: "fnv"
Go package: https://golang.org/pkg/hash/fnv/
Wikipedia: https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

**Comment by YassineE** [comment]
I am wondering in which context this operator can/should be used?

**Comment by tealeg** [comment]
@YassineE a hash can be used as a way to arbitrarily distribute a set of entities  - see also `percentile` which makes use of this property.

**Comment by YassineE** [comment]
Alright, a potential use case is:
- we hash a given value
- we see if it's included in a percentile thanks to the `percentile` operator

Useful for feature flipping, A/B testing, etc... Am I right?
