### ISSUE TITLE
Consult latest ruleset page

### ISSUE THREAD

**Issue by asdine** [heetch/regula#32]
Create a page that allows consulting the latest ruleset version

Path: `GET /rulesets/<path>/latest`
Get data from: `GET /i/rulesets/<path>`

Sketch: 
![regula-040-ruleset-latest](https://user-images.githubusercontent.com/2102036/48353186-16adc980-e68f-11e8-918b-33032700772d.png)

Related to #33

**Comment by YassineE** [comment]
Closing this fixed in #98.
