### ISSUE TITLE
Edit ruleset rules endpoint

### ISSUE THREAD

**Issue by asdine** [heetch/regula#36]
Endpoint: `PATCH /i/rulesets/<path>`

Expected payload :
```js
{
  "rules": [
        {
            "sExpr": "",
            "returnValue": "",
        }
    ]
}
```

The server must replace all the rules of the ruleset by the ones received in the request.

## Success
Response: 200

## Failure
Requirements: The `rules` field of the payload must contain at least one rule

Validation error:
```js
{ 
	"error": "validation",
	"fields": [
		{
			"path": ["rules", "2", "sExpr"],
			"error": {
				"message": "",
				"line": 10,
				"char": 11,
				"absChar": 120,
			}
		},
		{
			"path": ["rules", "2", "returnValue"],
			"error": {
				"message": "",
			}
		}
	]
}
```

**Comment by YassineE** [comment]
What do you mean by:
> "rules": [ //must contain all the rules

and

> Must contain at least one rule

?

**Comment by asdine** [comment]
@YassineE I have edited the issue with more details, tell me if it's ok for you

**Comment by YassineE** [comment]
Yes it's more than clear now. 👍

**Comment by tealeg** [comment]
I don't think its true that we have to pass rules  - passing an empty ruleset should be ok too. or am I missing something @asdine ?

**Comment by asdine** [comment]
Indeed It won't be true anymore once the signature PR will land
