### ISSUE TITLE
Evolving rulesets signature

### ISSUE THREAD

**Issue by YassineE** [heetch/regula#39]
The question has been brought by @Nyks06, how do we deal with evolving rulesets signature? 
The current design avoids to update the signature of an existing rulesets.

**Comment by jhchabran** [comment]
@YassineE did you reopen this by mistake? otherwise it's better to provide context on why it was reopened :)

**Comment by YassineE** [comment]
> @YassineE did you reopen this by mistake? otherwise it's better to provide context on why it was reopened :)

It wasn't close on purpose, miss click. 🙈
But if @Nyks06 is ok with the answer we can close it definitively.

**Comment by YassineE** [comment]
Closing this. @Nyks06 feel free to reopen if you need it.
