### ISSUE TITLE
Add debug log when trying to Put a rulesets which already exists

### ISSUE THREAD

**Issue by YassineE** [heetch/regula#50]
It will be better if we log (debug level) when trying to add an existing rulesets.

**Comment by asdine** [comment]
Can you give more details?

**Comment by YassineE** [comment]
The `Put` method checks if the given rulesets has the same checksum of the latest one (if it exists).
If it exists, it won't be stored to avoid duplicates thus it worth it to add a debug log. WDYT?

**Comment by YassineE** [comment]
Closing this, fixed in #55.
