### ISSUE TITLE
Default value is not supported anymore

### ISSUE THREAD

**Issue by asdine** [heetch/regula#68]
The UI is using `(#true)` as the default rule for any new ruleset.
When trying to create a new ruleset, an error is returned:

```
Expected an operator, but got the boolean \"true\"
```

**Comment by tealeg** [comment]
Because it should be:
`#true`
... not 
`(#true)`.
... Surely?

**Comment by asdine** [comment]
Indeed it works with `#true`, I changed the default rule to that value :+1:
