### ISSUE TITLE
Add Fnv operator

### ISSUE THREAD

**Issue by asdine** [heetch/regula#99]
Same behaviour as https://github.com/heetch/regula/blob/b79b8edceafa6f3c5d7461ba29f83cbbb94ddb40/rule/hash_expr.go#L36

**Comment by asdine** [comment]
Closing this as it's not really that useful for the v0.6, let's keep it for the v0.7

**Comment by tealeg** [comment]
Actually this is addressed in the branch to do `percentile`, so let's track that.
